Section "ServerFlags"
    Option "AutoAddDevices" "true"
    Option "AutoEnableDevices" "true"
EndSection

Section "ServerLayout"
    Identifier "layout"
    Screen "Screen0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Device0"
EndSection

Section "Device"
    Identifier "Device0"
    Driver "modesetting"
EndSection
